version: "3.3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - mynet
  psql:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
        - /data/postgres
    ports:
      - "5432:5432"
    networks:
      - mynet
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - /var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - mynet
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge